In [ ]:
import random
arr = [random.randint(1, 100) for _ in range(20)]
max_even = max((x for x in arr if x % 2 == 0), default=None)
print("Массив:", arr)
print("Максимальное четное число:", max_even)

Массив: [45, 74, 64, 28, 16, 19, 7, 51, 3, 80, 9, 93, 51, 19, 83, 54, 60, 84, 54, 12]
Максимальное четное число: 84


In [9]:
import numpy as np
матрица = np.array([
    [1, 2, 3, 2, 1],
    [4, 5, 6, 7, 8],
    [9, 8, 7, 8, 9]
])
result = [1 if np.array_equal(row, row[::-1]) else 0 for row in матрица]
print("Двумерный массив:")
print(матрица)
print("Результат:", result)

Двумерный массив:
[[1 2 3 2 1]
 [4 5 6 7 8]
 [9 8 7 8 9]]
Результат: [1, 0, 1]


In [11]:
N = int(input("Введите количество кеглей (N): "))
K = int(input("Введите количество бросков (K): "))
pins = ["I"] * N  
for _ in range(K):
    li, ri = map(int, input("Введите li и ri через пробел: ").split())
    for i in range(li - 1, ri):
        pins[i] = "."
print("Результат:", "".join(pins))


Результат: .....I..II


In [ ]:
gazeta = 75
journal = 27
both = 13
total_families = gazeta + journal - both
print("Количество семей в доме:", total_families)

Количество семей в доме: 89


In [ ]:
cube_dict = {x: x**3 for x in range(1, 11)}
print("Словарь кубов:", cube_dict)

Словарь кубов: {1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}
